---
title: "Body weight"
author: "Haipeng Sun"
date: "1/10/2022"
output: html_document
---

## library
```{r setup, message=FALSE, warning=FALSE}
library(readxl)
library(phyloseq)
library(usedist)
library(grid)
library(gridExtra)
library(gtable)
library(ggpubr)
library(lme4)
library(lmerTest)
library(nlme)
library(sjPlot)
library(gamlss)
library(epiR)
library(tidyverse)
```

## load data
```{r}
load(file = "../data/BW_and_phylo.RData")
temp_out = "../result/bodyweight/"
```

## plot data
### bodyweight
```{r}
g = ggplot(BW, aes(x = TimePoint_Weeks, color = BirthMode)) +
  geom_point(aes(y = Weight_g), size = 0.5, alpha = 0.7) +
  geom_path(aes(y = Weight_g , group = MouseID), size = 0.3, alpha = 0.3) + 
  geom_ribbon(data = BW_sum, alpha = 0.5, size = 0.1,
              aes(x = TimePoint_Weeks, ymin = boot.lo, ymax = boot.hi, 
                  group = BirthMode, color = BirthMode, fill = BirthMode)) + 
  geom_path(data = BW_sum, aes(x = TimePoint_Weeks, y = Mean, group = BirthMode)) + 
  facet_grid(.~Sex, labeller = labeller(Sex = Sex_labs)) +
  scale_x_continuous(breaks = c(2,4,6,8,10,12,14,16,18)) + 
  scale_color_manual(values = BirthMode_color, aesthetics = c("fill", "colour")) +
  labs(x = "Age (Week)", y = "Body Weight (g)", title = "") + 
  theme_bw() + theme(aspect.ratio = 0.8,
                     panel.background = element_rect(fill = NA),
                     strip.text = element_text(size=12,color="black",face='bold'),
                     axis.title = element_text(size=12,color="black",face='bold'),
                     axis.text = element_text(size=12,color="black",face='bold'),
                     axis.text.x = element_text(size=12,color="black",face='bold'),
                     axis.text.y = element_text(size=12,color="black",face='bold'),
                     legend.text = element_text(size=12,color="black",face='bold'),
                     legend.title = element_text(size=12,color="black",face='bold'),
                     title = element_text(size=12,color="black",face='bold'))
ggsave(filename = paste0(temp_out,"body_weight_overall.pdf"), device = cairo_pdf, 
         plot = g, width = 7, height = 5, units = "in", dpi = 300)
```

### plot BWgain
```{r}
g = ggplot(BWgain, aes(x = TimePoint_Weeks, color = BirthMode)) +
  geom_point(aes(y = BW_gain),size = 0.5, alpha = 0.7) +
  geom_path(aes(y = BW_gain, group = MouseID), size = 0.3, alpha = 0.2) +
  geom_ribbon(data = BWgain_sum, alpha = 0.3, size = 0.1,
              aes(x = TimePoint_Weeks, ymin = boot.lo, ymax = boot.hi, 
                  group = BirthMode, color = BirthMode, fill = BirthMode)) + 
  geom_path(data = BWgain_sum, aes(x = TimePoint_Weeks, y = Mean, group = BirthMode)) + 
  facet_grid(.~Sex,labeller = labeller(Sex = Sex_labs)) +
  scale_x_continuous(breaks = c(4,6,8,10,12,14,16,18)) +
  scale_color_manual(values = BirthMode_color, aesthetics = c("fill", "colour")) +
  labs(x = "Age (Week)", y = "Body Weight gain (g)", title = "") + 
  theme_bw() + theme(aspect.ratio = 0.8,
                     panel.background = element_rect(fill = NA),
                     strip.text = element_text(size=12,color="black",face='bold'),
                     axis.title = element_text(size=12,color="black",face='bold'),
                     axis.text = element_text(size=12,color="black",face='bold'),
                     axis.text.x = element_text(size=12,color="black",face='bold'),
                     axis.text.y = element_text(size=12,color="black",face='bold'),
                     legend.text = element_text(size=12,color="black",face='bold'),
                     legend.title = element_text(size=12,color="black",face='bold'),
                     title = element_text(size=12,color="black",face='bold'))
ggsave(filename = paste0(temp_out,"body_weight_gain_overall.pdf"), device = cairo_pdf,
       plot = g, width = 7, height = 5, units = "in", dpi = 300)

p = ggplot(BWgain, aes(x = TimePoint_Weeks, color = BirthMode)) +
  geom_point(aes(y = BW_gain_percent), size = 0.5, alpha = 0.7) +
  geom_path(aes(y = BW_gain_percent, group = MouseID), size = 0.3, alpha = 0.2) +
  geom_ribbon(data = BWgain_sum, alpha = 0.3, size = 0.1,
              aes(x = TimePoint_Weeks, ymin = boot_p.lo, ymax = boot_p.hi, 
                  group = BirthMode, color = BirthMode, fill = BirthMode)) + 
  geom_path(data = BWgain_sum, aes(x = TimePoint_Weeks, y = Mean_p, group = BirthMode)) + 
  facet_grid(.~Sex,labeller = labeller(Sex = Sex_labs)) +
  scale_x_continuous(breaks = c(4,6,8,10,12,14,16,18)) + 
  scale_y_continuous(breaks = c(1, 1.5, 2, 2.5, 3, 3.5, 4), labels = scales::percent) +
  scale_color_manual(values = BirthMode_color, aesthetics = c("fill", "colour")) +
  labs(x = "Age (Week)", y = "Body Weight gain (%)", title = "") + 
  theme_bw() + theme(aspect.ratio = 0.8,
                     panel.background = element_rect(fill = NA),
                     strip.text = element_text(size=12,color="black",face='bold'),
                     axis.title = element_text(size=12,color="black",face='bold'),
                     axis.text = element_text(size=12,color="black",face='bold'),
                     axis.text.x = element_text(size=12,color="black",face='bold'),
                     axis.text.y = element_text(size=12,color="black",face='bold'),
                     legend.text = element_text(size=12,color="black",face='bold'),
                     legend.title = element_text(size=12,color="black",face='bold'),
                     title = element_text(size=12,color="black",face='bold'))
ggsave(filename = paste0(temp_out,"body_weight_gain_percent_overall.pdf"), plot = p,
    width = 7, height = 5, units = "in", dpi = 300)
```

## LMM model
### LMM all
```{r eval=FALSE, include=TRUE}
plot_model_fit_table <- function(model, a_tab, terms = c("TimePoint_Weeks","BirthMode"), output, xlab, ylab, ...){
  require(sjPlot)
  p = plot_model(model, type = "pred", terms = terms,
               colors = BirthMode_color, ci.lvl = .95)
  xmin = ggplot_build(p)$layout$panel_scales_x[[1]]$range$range[1]
  xmax = ggplot_build(p)$layout$panel_scales_x[[1]]$range$range[2]
  ymin = ggplot_build(p)$layout$panel_scales_y[[1]]$range$range[1]
  ymax = ggplot_build(p)$layout$panel_scales_y[[1]]$range$range[2]
  p1 = plot_model(model, type = "pred", terms = terms,
               colors = BirthMode_color, ci.lvl = .95) + 
    scale_x_continuous(breaks = seq(from = 1, to = 18, by = 2)) + 
    scale_y_continuous(limits = c(ymin, ymax + (ymax - ymin)* 0.3)) + 
    labs(x = xlab, y = ylab, title = "") + 
      theme_bw() + theme(aspect.ratio = 0.8,
                     panel.background = element_rect(fill = NA),
                     strip.text = element_text(size=12,color="black",face='bold'),
                     axis.title = element_text(size=12,color="black",face='bold'),
                     axis.text = element_text(size=12,color="black",face='bold'),
                     axis.text.x = element_text(size=12,color="black",face='bold'),
                     axis.text.y = element_text(size=12,color="black",face='bold'),
                     legend.text = element_text(size=12,color="black",face='bold'),
                     legend.title = element_text(size=12,color="black",face='bold'),
                     title = element_text(size=12,color="black",face='bold'))
  p1 = p1 + annotation_custom(grob = tableGrob(a_tab, 
                                             theme = ttheme_minimal(base_size = 8)),
                     xmin = xmin, xmax = xmax, 
                     ymin = ymax, 
                     ymax = ymax + (ymax - ymin)* 0.3)
  ggsave(filename = output, plot = p1,
    width = 7, height = 5, units = "in", dpi = 300)
}

lmm_model_lme4 <- function(x, dir, ...){
  dat <- x$y
  S <- x$Sex
  if(dat=="Weight_g"){
    wdat = BW %>% filter(Sex == S)
    ylab <- "Body Weight (g)"
  }else{
    wdat = BWgain %>% filter(Sex == S)
    ylab = ifelse(dat == "BW_gain", "Body Weight Gain (g)","Body Weight Gain (%)")
  }
  fo <- paste0(dat, " ~ TimePoint_Weeks*BirthMode + (TimePoint_Weeks|MouseID)") %>% 
      as.formula()
  m <- lmer(fo, data = wdat,
            control = lmerControl(optimizer ="Nelder_Mead"), REML = F)
  a_tab <- anova(m) %>% as.data.frame() %>% 
      mutate(`Sum Sq` = round(`Sum Sq`,2),
             `Mean Sq` = round(`Mean Sq`,2),
             DenDF = round(DenDF,2),
             `F value` = round(`F value`,4),
             `Pr(>F)` = round(`Pr(>F)`,4)) %>% 
    as.data.frame()
  output <- paste0(dir,"LMM_", dat, "_in_", S, "_lme4.pdf")
  plot_model_fit_table(model = m, a_tab = a_tab,
                       terms = c("TimePoint_Weeks","BirthMode"), 
                       output = output, 
                       xlab = "Age (Week)", 
                       ylab = ylab)
} 

lmm_model_nlme <- function(x, dir, ...){
  dat <- x$y
  S <- x$Sex
  if(dat=="Weight_g"){
    wdat = BW %>% filter(Sex == S)
    ylab <- "Body Weight (g)"
  }else{
    wdat = BWgain %>% filter(Sex == S)
    ylab = ifelse(dat == "BW_gain", "Body Weight Gain (g)","Body Weight Gain (%)")
  }
  fo <- paste0(dat, " ~ TimePoint_Weeks*BirthMode") %>% as.formula()
  m <- lme(fo, random = ~ 1 + TimePoint_Weeks|MouseID, 
            data = wdat)
  a_tab <- anova(m) %>%  filter(rownames(.) != "(Intercept)") %>% 
      mutate(`F-value` = round(`F-value`,4),
             `p-value` = round(`p-value`,4)) %>% as.data.frame()
  output <- paste0(dir,"LMM_", dat, "_in_", S, "_nlme.pdf")
  plot_model_fit_table(model = m, a_tab = a_tab,
                       terms = c("TimePoint_Weeks","BirthMode"), 
                       output = output, 
                       xlab = "Age (Week)", 
                       ylab = ylab)
}
dir = paste0(temp_out,"")
model_input = list(Sex = c("M", "F"), y = c("Weight_g", "BW_gain", "BW_gain_percent")) %>% cross()
map(model_input, lmm_model_lme4, dir = dir)
map(model_input, lmm_model_nlme, dir = dir) # Error in eval(x$call$fixed) : object 'fo' not found 
```


### LMM explore
```{r}
fit = lm(Weight_g ~ TimePoint_Weeks*BirthMode + Sex + LitterSize_Born, data = BW)
summary(fit)
fit_lme4 = lmer(Weight_g ~ TimePoint_Weeks*BirthMode + Sex + LitterSize_Born + (TimePoint_Weeks|MouseID), 
                data = BW,
                        control = lmerControl(optimizer ="Nelder_Mead"), REML = F)
summary(fit_lme4)
fit_nlme = lme(Weight_g ~ TimePoint_Weeks*BirthMode + Sex + LitterSize_Born, 
               random = ~ 1 + TimePoint_Weeks|MouseID, data = BW)
summary(fit_nlme)

fitgain = lm(BW_gain ~ TimePoint_Weeks*BirthMode + Sex + LitterSize_Born, data = BWgain)
summary(fitgain)
fitgain_lme4 = lmer(BW_gain ~ TimePoint_Weeks*BirthMode + Sex + LitterSize_Born + (TimePoint_Weeks|MouseID), data = BWgain,
                        control = lmerControl(optimizer ="Nelder_Mead"), REML = F)
summary(fitgain_lme4)
fitgain_nlme = lme(BW_gain ~ TimePoint_Weeks*BirthMode + Sex + LitterSize_Born, 
               random = ~ 1 + TimePoint_Weeks|MouseID, data = BWgain)
summary(fitgain_nlme)

fitgainp = lm(BW_gain_percent ~ TimePoint_Weeks*BirthMode + Sex + LitterSize_Born, data = BWgain)
summary(fitgainp)
fitgainp_lme4 = lmer(BW_gain_percent ~ TimePoint_Weeks*BirthMode+ LitterSize_Born + Sex + (TimePoint_Weeks|MouseID), data = BWgain,
                        control = lmerControl(optimizer ="Nelder_Mead"), REML = F)
summary(fitgainp_lme4)
fitgainp_nlme = lme(BW_gain_percent ~ TimePoint_Weeks*BirthMode + Sex + LitterSize_Born, 
                    random = ~ 1 + TimePoint_Weeks|MouseID, data = BWgain)
summary(fitgainp_nlme)
```

## overweight on percentile
### percentile calculate
```{r}
BW_f <- BW %>% filter(Sex == "F") %>% dplyr::select(Weight_g, TimePoint_Weeks)
centile_BW_f_model <-  gamlss::lms(Weight_g, TimePoint_Weeks, data = BW_f, families = "BCT")
BW_f_centile <- gamlss::centiles.pred(centile_BW_f_model, xname = "TimePoint_Weeks", 
                             xvalues = c(2:18), cent=c(15, 20, 25, 50, 75, 80, 85)) 

BW_m <- BW %>% filter(Sex == "M") %>% dplyr::select(Weight_g, TimePoint_Weeks) 
centile_BW_m_model =  gamlss::lms(Weight_g, TimePoint_Weeks, data = BW_m, families = "BCT")
BW_m_centile = gamlss::centiles.pred(centile_BW_m_model, xname = "TimePoint_Weeks", 
                             xvalues = c(2:18), cent=c(15, 20, 25, 50, 75, 80, 85)) 
```

### BW status 
```{r}
at_week15 <- BW %>% filter(TimePoint_Weeks == 15) %>% 
  mutate(BW_status = 
         case_when(Sex == "F" & Weight_g < BW_f_centile[which(BW_f_centile$x == 15), "20"] ~ "Underweight",
                   Sex == "M" & Weight_g < BW_m_centile[which(BW_m_centile$x == 15), "20"] ~ "Underweight",
                   Sex == "F" & Weight_g <= BW_f_centile[which(BW_f_centile$x == 15), "80"] ~ "Normal",
                   Sex == "M" & Weight_g <= BW_m_centile[which(BW_m_centile$x == 15), "80"] ~ "Normal",
                   Sex == "F" & Weight_g > BW_f_centile[which(BW_f_centile$x == 15), "80"] ~ "Overweight",
                   Sex == "M" & Weight_g > BW_m_centile[which(BW_m_centile$x == 15), "80"] ~ "Overweight"),
         Overweight = ifelse(BW_status == "Overweight", "Y", "N"),
         Underweight = ifelse(BW_status == "Underweight", "Y", "N")
         )

save(BW_f_centile, BW_m_centile, at_week15,
     file = paste0("../data/BW_responder.RData"))
```

### plot
```{r}
dat <- BW %>% left_join(at_week15 %>% select(MouseID, BW_status, Overweight, Underweight), 
                        by = "MouseID") %>% 
  filter(!is.na(BW_status)) 

dat_centile <- rbind(BW_f_centile %>% transmute(TimePoint_Weeks = x, Sex = "F", BW20 = `20`, BW50 = `50`, BW80 = `80`),
                     BW_m_centile %>% transmute(TimePoint_Weeks = x, Sex = "M", BW20 = `20`, BW50 = `50`, BW80 = `80`))

g = ggplot(dat, aes(x = TimePoint_Weeks)) +
  geom_point(data = dat %>% filter(Overweight == "N"), 
             aes(x = TimePoint_Weeks, y = Weight_g), color = "Gray50", size = 0.5, alpha = 0.5) +
  geom_path(data = dat %>% filter(Overweight == "N"),
             aes(x = TimePoint_Weeks, y = Weight_g , group = MouseID), color = "Gray50", size = 0.3, alpha = 0.5) + 
  geom_ribbon(data = dat_centile, alpha = 0.3, size = 0.1,
              aes(x = TimePoint_Weeks, ymin = BW20, ymax = BW80)) + 
  geom_path(data = dat_centile, aes(x = TimePoint_Weeks, y = BW50)) + 
  geom_point(data = dat %>% filter(Overweight == "Y"),
             aes(x = TimePoint_Weeks, y = Weight_g, color = BirthMode), size = 1, alpha = 1) +
  geom_path(data = dat %>% filter(Overweight == "Y"),
             aes(x = TimePoint_Weeks, y = Weight_g , group = MouseID, color = BirthMode ), size = 0.5, alpha = 1) +   
  facet_grid(.~Sex, labeller = labeller(Sex = Sex_labs)) +
  scale_x_continuous(breaks = c(2,4,6,8,10,12,14,16,18)) + 
  scale_color_manual(values = BirthMode_color, aesthetics = c("fill", "colour")) +
  labs(x = "Age (Week)", y = "Body Weight (g)", title = "") + 
  theme_bw() + theme(aspect.ratio = 1,
                     panel.background = element_rect(fill = NA),
                     strip.text = element_text(size=12,color="black",face='bold'),
                     axis.title = element_text(size=12,color="black",face='bold'),
                     axis.text = element_text(size=12,color="black",face='bold'),
                     axis.text.x = element_text(size=12,color="black",face='bold'),
                     axis.text.y = element_text(size=12,color="black",face='bold'),
                     legend.text = element_text(size=12,color="black",face='bold'),
                     legend.title = element_text(size=12,color="black",face='bold'),
                     title = element_text(size=12,color="black",face='bold'))
ggsave(filename = paste0(temp_out,"body_weight_overweight.pdf"), device = cairo_pdf, 
         plot = g, width = 7, height = 5, units = "in", dpi = 300)
```

### test
```{r}
tab_f = at_week15 %>% filter(Sex == "F") %>% 
  dplyr::select(BirthMode, Overweight) %>% table() %>% as.matrix()
fisher.test(tab_f)

epi.2by2(dat = tab_f[c("CS","VF")  ,c("Y","N")], 
         method = "cohort.count", digits = 2, outcome = "as.columns")
epi.2by2(dat = tab_f[c("CSR","VF")  ,c("Y","N")], 
         method = "cohort.count", digits = 2, outcome = "as.columns")
epi.2by2(dat = tab_f[c("CSR","CS")  ,c("Y","N")], 
         method = "cohort.count", digits = 2, outcome = "as.columns")

tab_m = at_week15 %>% filter(Sex == "M") %>% 
  dplyr::select(BirthMode, Overweight) %>% table() %>% as.matrix()
fisher.test(tab_m)

epi.2by2(dat = tab_m[c("CS","VF")  ,c("Y","N")], 
         method = "cohort.count", digits = 2, outcome = "as.columns")
epi.2by2(dat = tab_m[c("CSR","VF")  ,c("Y","N")], 
         method = "cohort.count", digits = 2, outcome = "as.columns")
epi.2by2(dat = tab_m[c("CSR","CS")  ,c("Y","N")], 
         method = "cohort.count", digits = 2, outcome = "as.columns")
```












