---
title: "Taxa"
author: "Haipeng Sun"
date: "7/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## library
```{r message=FALSE, warning=FALSE, include=FALSE}
library(phyloseq)
library(Hmisc)
library(agricolae)
library(grid)
library(gridExtra)
library(gtable)
library(ggrepel)
library(phyloseq)
library(usedist)
library(purrr)
library(furrr)
library(vegan)
library(ape)
library(rlist)
library(ggpubr)
library(tidyverse)
```

## load data
```{r}
load(file = "../data/BW_and_phylo.RData")
temp_out = "../result/taxa/"
```

## masslin2
### function
```{r message=FALSE, warning=FALSE, include=FALSE}
library(Maaslin2)
### function wrap for all taxa levels
#in put metadata, sample id column name, phyloseq object
do_maaslin2 = function(meta, sample_id, phylo_rf, fixed, random, ref, output, 
                       min_prevalence = 0.1, min_abundance = 0.0, max_significance = 0.1,
                       normalization = "TSS", transform = "LOG",analysis_method = "LM",
                       plot_heatmap	= FALSE, plot_scatter = FALSE, cores = 1){
  ft = otu_table(phylo_rf@otu_table) %>% as.matrix() %>% as.data.frame() %>% rownames_to_column(var = "id")
  wft = ft %>% select(id,  meta %>% pull(sample_id)) %>% column_to_rownames(var = "id") %>% t()
  wmeta = meta %>% column_to_rownames(var = sample_id)
  taxrank = "ASV"
  fit = Maaslin2(
    input_data = wft, 
    input_metadata = wmeta, 
    normalization = normalization,
    transform = transform,
    analysis_method = analysis_method,
    output = paste0(output,"_",taxrank),
    plot_heatmap = plot_heatmap,
    plot_scatter = plot_scatter,
    fixed_effects = fixed,
    reference = ref,
    random_effects = random,
    min_prevalence = min_prevalence,
    min_abundance = min_abundance,
    max_significance = max_significance,
    cores = cores
  )
  for (taxrank in c("Species","Genus","Family","Order","Class","Phylum")){
  phylo_glom = tax_glom(phylo_rf, taxrank = taxrank, NArm = F)
  ft_glom = otu_table(phylo_glom@otu_table) %>% as.matrix() %>% as.data.frame() %>% rownames_to_column(var = "id")
  wft = ft_glom %>% select(id, meta %>% pull(sample_id)) %>% column_to_rownames(var = "id") %>% t()
  fit = Maaslin2(
      input_data = wft, 
      input_metadata = wmeta, 
      normalization = normalization,
      transform = transform,
      analysis_method = analysis_method,
      output = paste0(output,"_",taxrank),
      plot_heatmap = plot_heatmap,
      plot_scatter = plot_scatter,
      fixed_effects = fixed,
      reference = ref,
      random_effects = random,
      min_prevalence = min_prevalence,
      min_abundance = min_abundance,
      max_significance = max_significance,
      cores = cores
      )
  }
}

summarise_maaslin2 = function(path, group, taxa){
  res = matrix(data = NA, nrow = 1, ncol = 20)
  res = as.data.frame(res)
  names(res) =  c("feature","metadata","value","coef","stderr","N","N.not.0","pval","qval","Group",
                  "id","Kingdom","Phylum","Class","Order","Family","Genus","Species","ASV", "level")
  for (taxrank in c("ASV", "Species", "Genus", "Family", "Order", "Class", "Phylum")){
    a = read.table(file = paste0(path ,"_", taxrank, "/significant_results.tsv"),
                  header = T, sep = "\t", stringsAsFactors = F)
    if (nrow(a) == 0) {next}
    a = a %>% mutate(Group = group, id = str_remove(feature,"^X"),feature = str_remove(feature,"^X")) %>% left_join(taxa, by = "id") %>% mutate(level = taxrank)
    res = rbind(res,a)
  }
  res = res %>% filter(!is.na(feature))
  res
}
```

### compare
```{r message=FALSE, warning=FALSE, include=FALSE}
output = paste0(temp_out, "maaslin2/")
meta = phylo_decomtan_rf@sam_data@.Data %>% as.data.frame()
names(meta) = phylo_decomtan_rf@sam_data@names
meta$SampleID = phylo_decomtan_rf@sam_data@row.names

meta = meta %>%  filter(Generation == "F1") %>% mutate(TimePoint = as.character(TimePoint))
#### include all timepoint
fit = do_maaslin2(meta = meta, sample_id = "SampleID", phylo_rf = phylo_decomtan_rf, 
                  fixed = c("BirthMode", "Sex", "TimePoint"), 
                  random = c("MouseID"), 
                  ref = c("BirthMode,VF", "Sex,F", "TimePoint,Week3"), 
                  output = paste0(output,"All_timepoint"),
                  cores = 4
                  )
res = summarise_maaslin2(path = paste0(output,"All_timepoint"), group = "compare_all", taxa)
write.csv(res, file = paste0(output,"All_timepoint_summary.csv"),quote = F, row.names = F)
#### by time points
for (tp in meta$TimePoint %>% unique()){
  wmeta = meta %>% filter(TimePoint == tp)
  fit = do_maaslin2(meta = wmeta, sample_id = "SampleID", phylo_rf = phylo_decomtan_rf, 
                  fixed = c("BirthMode", "Sex"), 
                  random = NULL, 
                  ref = c("BirthMode,VF", "Sex,F"), 
                  output = paste0(output,tp),
                  cores = 4
                  )
  res = summarise_maaslin2(path = paste0(output,tp), group = tp, taxa)
  write.csv(res, file = paste0(output, tp, "_summary.csv"),quote = F, row.names = F)  
} 

```

## ancom
### function
```{r include=FALSE}
library(ANCOMBC)
### function wrap
do_ancombc = function(phyloseq = phylo_wk, formula = "BirthMode+Sex+TimePoint",
                      p_adj_method = "BH", prv_cut = 0.1, lib_cut = 0,
                      group = NULL, struc_zero = FALSE, neg_lb = FALSE,
                      tol = 1e-05, max_iter = 100, conserve = FALSE, 
                      alpha = 0.05, global = FALSE, 
                      taxa = taxa){
  taxrank = "ASV"
  outbc <- ancombc(phyloseq = phylo_wk, 
               formula = formula,
               p_adj_method = p_adj_method, prv_cut = prv_cut, lib_cut = lib_cut, 
               group = group, struc_zero = struc_zero, neg_lb = neg_lb,
               tol = tol, max_iter = max_iter, conserve = conserve, 
               alpha = alpha, global = global)
  res1 <- as.data.frame(outbc$res) %>% rownames_to_column(var = "id") %>%
    left_join(taxa, by = "id") %>% mutate(level = taxrank)
  
  res_lst <- lapply(c("Species","Genus","Family","Order","Class","Phylum"), function(taxrank){
    phylo_glom = tax_glom(phylo_wk, taxrank = taxrank, NArm = F)
    outbc <- ancombc(phyloseq = phylo_glom, 
                 formula = formula,
                 p_adj_method = p_adj_method, prv_cut = prv_cut, lib_cut = lib_cut, 
                 group = group, struc_zero = struc_zero, neg_lb = neg_lb,
                 tol = tol, max_iter = max_iter, conserve = conserve, 
                 alpha = alpha, global = global)   
    res <- as.data.frame(outbc$res) %>% rownames_to_column(var = "id") %>%
      left_join(taxa, by = "id") %>% mutate(level = taxrank)    
    res
  })
    res2 = do.call(rbind, res_lst)
    res <- rbind(res1, res2)
    res
}

```


### compare
```{r include=FALSE}
output = paste0(temp_out, "ancom/")
meta = phylo_decomtan_rf@sam_data@.Data %>% as.data.frame()
names(meta) = phylo_decomtan_rf@sam_data@names
meta$SampleID = phylo_decomtan_rf@sam_data@row.names

meta = meta %>%  filter(Generation == "F1") %>% mutate(TimePoint = as.character(TimePoint))
#### include all timepoint
phylo_wk <- prune_samples(meta$SampleID, phylo_decomtan_rf)

outbc <- ancombc(phyloseq = phylo_wk, 
               formula = "BirthMode+Sex+TimePoint",
               p_adj_method = "BH", prv_cut = 0.1, lib_cut = 0, 
               group = "BirthMode", struc_zero = TRUE)
a <- as.data.frame(outbc$res) %>% rownames_to_column(var = "id") %>%
  left_join(taxa, by = "id") %>% 
  mutate(level = "ASV")


aa <- do_ancombc(phyloseq = phylo_wk,
                 formula = "BirthMode+Sex+TimePoint", 
                 taxa = taxa)







```



## compare different methods
```{r}
# with week 12 pups M facility
# masslin2
a = read.csv("output/taxa/maaslin2/summary_pups_M_Week12.csv")
picked_maaslin2 = a %>% filter(metadata == "Facility", level == "ASV") %>% pull(feature)
# ancom2
a = read.csv("output/taxa/ancom/pup_Facility_M_Week12_ASV_res.csv")
picked_ancom2 = a %>% pull(taxa_id) 
# aldex2
a = read.csv("output/taxa/aldex2/pup_M_Week12_ASV_res.csv")
picked_aldex2 = a %>% filter(str_detect(model, "Facility"), PrtBH < 0.1) %>% pull(id)
# venn
library(gplots)

a = venn(list("aldex"=picked_aldex2, "ancom"=picked_ancom2, "maaslin"=picked_maaslin2), 
         show.plot = F, intersections = F)
a
# valcano plot
log2FC_lm_estimate = function(wft, wmeta, fo, Var){
  # estimate log2 fold change using log10 transformed RA with simplified lm model
  coef_p_l = split(wft, rownames(wft)) %>% lapply(., function(x){
      log_RA = t(x)
      colnames(log_RA) = "log_RA"
      coefd = (merge(log_RA, wmeta, by.x = 0, by.y = "Sample_name") %>%
                 lm(formula = as.formula(fo), data = .) %>%
                 summary())$coefficients
      coefd[which(str_detect(rownames(coefd), Var)),c("Estimate", "Pr(>|t|)")]
      })
  coef_and_p = do.call(rbind.data.frame, coef_p_l)
  names(coef_and_p) = c("coef","pvalue")
  rownames(coef_and_p) = names(coef_p_l)
  coef_and_p$padj = p.adjust(coef_and_p$pvalue, method = "BH")
  coef_and_p$Log2FC = log2(10^coef_and_p$coef)
  coef_and_p
}

all_asv = c(picked_aldex2,picked_ancom2,picked_maaslin2) %>% unique()
wmeta = meta_16S %>% filter(Generation == "F1", Sex == "M", SamplingTimepoint == "Week12")
ft = otu_table(phylo_rf@otu_table) %>% as.matrix() %>% as.data.frame() 
wft = ft[all_asv, wmeta %>% pull(Sample_name)]
wft = log10((wft + 1)/colSums(ft)[1])
fo = "log_RA ~ TREATMENT + Facility "
Var = "Facility"

coef_and_p = log2FC_lm_estimate(wft, wmeta,
                       fo = "log_RA ~ TREATMENT + Facility",
                       Var = "TREATMENT")

coef_and_p = coef_and_p %>% rownames_to_column(var = "taxa") %>% 
  mutate(aldex = ifelse(taxa %in% picked_aldex2, "Y", "N"),
         ancom = ifelse(taxa %in% picked_ancom2, "Y", "N"),
         maaslin = ifelse(taxa %in% picked_maaslin2, "Y", "N"))
  
p1 = ggplot(data = coef_and_p, aes(x=Log2FC, y = -log10(pvalue))) + 
  geom_point(aes(color = aldex)) + 
  geom_vline(xintercept=c(-1,-0.5, 0.5,  1), col="red") + 
  geom_hline(yintercept=-log10(0.05), col="red") + 
  scale_color_manual(values = c("gray","red"))

p2 = ggplot(data = coef_and_p, aes(x=Log2FC, y = -log10(pvalue))) + 
  geom_point(aes(color = ancom)) + 
  geom_vline(xintercept=c(-1,-0.5, 0.5,  1), col="red") + 
  geom_hline(yintercept=-log10(0.05), col="red") + 
  scale_color_manual(values = c("gray","red"))

p3 = ggplot(data = coef_and_p, aes(x=Log2FC, y = -log10(pvalue))) + 
  geom_point(aes(color = maaslin)) + 
  geom_vline(xintercept=c(-1,-0.5, 0.5,  1), col="red") + 
  geom_hline(yintercept=-log10(0.05), col="red") +
  scale_color_manual(values = c("gray","red"))


```








## heatmaps
```{r message=FALSE, warning=FALSE, include=FALSE}
library(ComplexHeatmap)
### function wrap
log2FC_lm_estimate = function(wft, wmeta,taxa_id, fo, Var){
  # estimate log2 fold change using log10 transformed RA with simplified lm model
  coef_p_l = split(wft, wft[taxa_id]) %>% lapply(., function(x){
      log_RA = t(x[,-1])
      colnames(log_RA) = "log_RA"
      coefd = (merge(log_RA, wmeta, by.x = 0, by.y = "Sample_name") %>%
                 lm(formula = as.formula(fo), data = .) %>%
                 summary())$coefficients
      coefd[which(str_detect(rownames(coefd), Var)),c("Estimate", "Pr(>|t|)")]
      })
  coef_and_p = do.call(rbind.data.frame, coef_p_l)
  names(coef_and_p) = c("coef","pvalue")
  rownames(coef_and_p) = names(coef_p_l)
  coef_and_p$padj = p.adjust(coef_and_p$pvalue, method = "BH")
  coef_and_p$Log2FC = log2(10^coef_and_p$coef)
  coef_and_p
}

mat_col_fun = circlize::colorRamp2(c(-4, -3.3, -2.6, -1.9, -1.2, -0.5), c("#253494","#2c7fb8","#41b6c4", "#7fcdbb", "#c7e9b4", "#ffffcc"))
col_fun = circlize::colorRamp2(c(-2, 0, 2), c("green", "white", "red"))
```


#### compare maaslin and ancom difference
```{r message=FALSE, warning=FALSE, include=FALSE}
#### ancom
a = lapply(c("Week3","Week4","Week5","Week7","Week9","Week12"),
           function(x){read.csv(paste0("output/taxa/ancom/summary_pups_TREATMENT_",x, ".csv"))})  
res_a_pup_TREATMENT = do.call(rbind, a) 
res_a_pup_TREATMENT_asv = res_a_pup_TREATMENT %>% filter(level == "ASV") %>% select(taxa_id, CLR_diff, Group) %>% 
  pivot_wider(names_from = "Group", values_from = "CLR_diff")
res_a_pup_TREATMENT_g = res_a_pup_TREATMENT %>% filter(level == "Genus") %>% select(taxa_id, CLR_diff, Group) %>% 
  pivot_wider(names_from = "Group", values_from = "CLR_diff")

a = lapply(c("Week3","Week4","Week5","Week7","Week9","Week12"),
           function(x){read.csv(paste0("output/taxa/ancom/summary_pups_Facility_",x, ".csv"))})  
res_a_pup_Facility = do.call(rbind, a)  
res_a_pup_Facility_asv = res_a_pup_Facility %>% filter(level == "ASV") %>% select(taxa_id, CLR_diff, Group) %>% 
  pivot_wider(names_from = "Group", values_from = "CLR_diff")
res_a_pup_Facility_g = res_a_pup_Facility %>% filter(level == "Genus") %>% select(taxa_id, CLR_diff, Group) %>% 
  pivot_wider(names_from = "Group", values_from = "CLR_diff")

#### maaslin
a = lapply(c("Week3","Week4","Week5","Week7","Week9","Week12"),
           function(x){read.csv(paste0("output/taxa/maaslin2/summary_pups_",x, ".csv"))})  
res_m_pup_sum = do.call(rbind, a)  

res_m_pup_TREATMENT_asv = res_m_pup_sum %>% filter(metadata == "TREATMENT",level == "ASV") %>% select(feature, coef, Group) %>% pivot_wider(names_from = "Group", values_from = "coef")
res_m_pup_TREATMENT_g = res_m_pup_sum %>% filter(metadata == "TREATMENT",level == "Genus") %>% select(feature, coef, Group) %>% pivot_wider(names_from = "Group", values_from = "coef")

res_m_pup_Facility_asv = res_m_pup_sum %>% filter(metadata == "Facility",level == "ASV") %>% select(feature, coef, Group) %>% pivot_wider(names_from = "Group", values_from = "coef")
res_m_pup_Facility_g = res_m_pup_sum %>% filter(metadata == "Facility",level == "Genus") %>% select(feature, coef, Group) %>% pivot_wider(names_from = "Group", values_from = "coef")

#### diff
a = gplots::venn(list(m = res_m_pup_Facility_asv %>% pull(feature), a = res_a_pup_Facility_asv %>% pull(taxa_id)), show.plot = F)
attr(a, "class") = NULL
attr(a, "intersections") = NULL
a

a = gplots::venn(list(m = res_m_pup_TREATMENT_asv %>% pull(feature), a = res_a_pup_TREATMENT_asv %>% pull(taxa_id)), show.plot = F)
attr(a, "class") = NULL
attr(a, "intersections") = NULL
a

a = gplots::venn(list(m = res_m_pup_Facility_g %>% pull(feature), a = res_a_pup_Facility_g %>% pull(taxa_id)), show.plot = F)
attr(a, "class") = NULL
attr(a, "intersections") = NULL
a

a = gplots::venn(list(m = res_m_pup_TREATMENT_g %>% pull(feature), a = res_a_pup_TREATMENT_g %>% pull(taxa_id)), show.plot = F)
attr(a, "class") = NULL
attr(a, "intersections") = NULL
a

```

#### maaslin2 heatmap genus
```{r include=FALSE}
################## pup treatment
picked_taxa = res_m_pup_TREATMENT_g %>% pull(feature)
taxa_new = taxa %>% mutate(taxa_long = str_c(Kingdom,Phylum,Class,Order,Family,Genus,sep = ";"))

meta_all = phylo_rf@sam_data@.Data %>% as.data.frame()
names(meta_all) = phylo_rf@sam_data@names
meta_all$Sample_name = phylo_rf@sam_data@row.names

wmeta = meta_all %>% filter(Generation == "F1") %>% 
  mutate(SamplingTimepoint = factor(SamplingTimepoint, levels = c("Week3","Week4","Week5","Week7","Week9","Week12"), ordered = T)) %>% 
  arrange(SamplingTimepoint,TREATMENT, Facility)
phylo_g = tax_glom(phylo_rf, taxrank = "Genus", NArm = F)
ft = otu_table(phylo_g@otu_table) %>% as.matrix() %>% as.data.frame() 
wft = ft[picked_taxa, wmeta %>% pull(Sample_name)]
wft = log10((wft + 1)/colSums(ft[,-1])[1])
wft = wft %>% rownames_to_column(var="id") %>% merge(taxa_new %>% select(id, taxa_long)) %>% select(!id) %>% select(taxa_long, everything())
#### estimate log2FC, looks like Maaslin2 coef is the log2FC, Chlorinated water as ref
coef_and_p = log2FC_lm_estimate(wft, wmeta, taxa_id = "taxa_long",
                       fo = "log_RA ~ TREATMENT + Facility + Sex",
                       Var = "TREATMENT")
#### annotation information 
df_col = wmeta %>% select(SamplingTimepoint, TREATMENT, Facility)
column_ha = HeatmapAnnotation(df = df_col %>% select(SamplingTimepoint, TREATMENT, Facility), 
                              col = list(SamplingTimepoint = col_timepoint_pup,
                                         TREATMENT = col_treatment, 
                                         Facility = col_facility),
                              simple_anno_size = unit(3, "mm"), 
                              annotation_label = c("Time point", "Treatment", "Facility"),
                              annotation_name_gp = gpar(fontsize = 7,fontface = "bold"), 
                              annotation_name_side = "left")
wft2 = wft %>% column_to_rownames(var = "taxa_long")
df_row_name_label = structure(rownames(wft2), names = rownames(wft2))
row_dend = as.dendrogram(hclust(dist(wft2)))
#### the heatmap below don't cluster column(sample), so samples are in orders
p = Heatmap(as.matrix(wft2), 
            col = mat_col_fun, 
            name = "Relative Abundance",
            heatmap_legend_param = list(at = c(-4, -3.3, -2.6, -1.9, -1.2, -0.5), 
                                        labels = c("0.01%", "0.05%", "0.25%", "1.25%", "6.25%", "31.25%"), 
                                        labels_gp = gpar(fontsize = 7), 
                                        title_gp = gpar(fontsize = 8, fontface = "bold")),
            cluster_columns = F, show_column_names = F,
            column_title_gp = gpar(fontsize = 7, fontface = "bold"),
            column_split = df_col$SamplingTimepoint,
            cluster_rows = row_dend,
            row_names_gp = gpar(fontsize = 8),
            row_labels = df_row_name_label,
            row_dend_width = unit(15, "mm"),
            row_names_max_width = max_text_width(df_row_name_label, gp = gpar(fontsize = 8)),
            top_annotation = column_ha,
            height = unit(8, "mm")*dim(wft)[1],
            width = unit(0.5, "mm")*dim(wft)[2]
            )
p1 = draw(p, heatmap_legend_side = "left", annotation_legend_side = "left")
pdf(file = paste0("output/taxa/maaslin2/pup_treatment_by_week_heatmap_g.pdf"), 
    width = ComplexHeatmap:::width(p1) %>% as.numeric()/25.4, 
    height = ComplexHeatmap:::height(p1) %>% as.numeric()/25.4, useDingbats = F)
draw(p1)
dev.off()

row_ord = row_order(p1)
taxa_ord = rownames(wft2)[row_ord]
## all genus coef data
a = lapply(c("Week3","Week4","Week5","Week7","Week9","Week12"),
           function(x){res = read.delim(paste0("output/taxa/maaslin2/pups_",x, "_Genus/all_results.tsv"))
                       res$Group = x
                       res
           })  
res_m_pup_g = do.call(rbind, a) %>% mutate(feature = str_remove(feature,"^X")) %>% 
  left_join(taxa_new %>% select(id, taxa_long),by = c("feature"="id"))

mat1 = res_m_pup_g %>% filter(taxa_long %in% taxa_ord, metadata == "TREATMENT") %>% 
  select(taxa_long, Group, coef) %>% pivot_wider(names_from = "Group", values_from = "coef") %>% 
  column_to_rownames(var = "taxa_long")
mat1 = mat1[taxa_ord,]

mat2 = res_m_pup_g %>% filter(taxa_long %in% taxa_ord, metadata == "TREATMENT") %>% 
  select(taxa_long, Group, qval) %>% 
  mutate(qval = ifelse(qval< 0.1, as.character(round(qval,4)),"")) %>% 
  pivot_wider(names_from = "Group", values_from = "qval") %>% 
  column_to_rownames(var = "taxa_long")
mat2 = mat2[taxa_ord,]

df_row_name_label = structure(rownames(mat1), names = rownames(mat1))
p = Heatmap(as.matrix(mat1), 
            col = col_fun, 
            name = "Log2 Fold Change",
            heatmap_legend_param = list(at = c(-2, -1, 0, 1, 2), 
                                        labels = c("-2", "-1", "0", "1", "2"), 
                                        labels_gp = gpar(fontsize = 7), 
                                        title_gp = gpar(fontsize = 8, fontface = "bold")),
            cluster_columns = F, show_column_names = T,
            column_title_gp = gpar(fontsize = 7, fontface = "bold"),
            cluster_rows = F,
            row_names_gp = gpar(fontsize = 8),
            row_labels = df_row_name_label,
            row_dend_width = unit(15, "mm"),
            row_names_max_width = max_text_width(df_row_name_label, gp = gpar(fontsize = 8)),
            cell_fun = function(j,i, x, y, width, height, fill){
              grid.text(sprintf("%s", mat2[i, j]), x, y, gp = gpar(fontsize = 7))
            },
            height = unit(5, "in"),
            width = unit(10, "in")
            )
p1 = draw(p, heatmap_legend_side = "left", annotation_legend_side = "left")
pdf(file = paste0("output/taxa/maaslin2/pup_treatment_by_week_heatmap_g_qval_fc.pdf"), 
    width = ComplexHeatmap:::width(p1) %>% as.numeric()/25.4, 
    height = ComplexHeatmap:::height(p1) %>% as.numeric()/25.4,
    useDingbats = F)
draw(p1)
dev.off()

############# pup facility
picked_taxa = res_m_pup_Facility_g %>% pull(feature)
picked_taxa = picked_taxa[which(abs(res_m_pup_Facility_g[,-1]) %>% apply(., 1, FUN = min, na.rm = T) > 0.8)]
taxa_new = taxa %>% mutate(taxa_long = str_c(Kingdom,Phylum,Class,Order,Family,Genus,sep = ";"))

meta_all = phylo_rf@sam_data@.Data %>% as.data.frame()
names(meta_all) = phylo_rf@sam_data@names
meta_all$Sample_name = phylo_rf@sam_data@row.names

wmeta = meta_all %>% filter(Generation == "F1") %>% 
  mutate(SamplingTimepoint = factor(SamplingTimepoint, levels = c("Week3","Week4","Week5","Week7","Week9","Week12"), ordered = T)) %>% 
  arrange(SamplingTimepoint, Facility,TREATMENT)
phylo_g = tax_glom(phylo_rf, taxrank = "Genus", NArm = F)
ft = otu_table(phylo_g@otu_table) %>% as.matrix() %>% as.data.frame() 
wft = ft[picked_taxa, wmeta %>% pull(Sample_name)]
wft = log10((wft + 1)/colSums(ft[,-1])[1])
wft = wft %>% rownames_to_column(var="id") %>% merge(taxa_new %>% select(id, taxa_long)) %>% select(!id) %>% select(taxa_long, everything())

#### annotation information 
df_col = wmeta %>% select(SamplingTimepoint, Facility, TREATMENT)
column_ha = HeatmapAnnotation(df = df_col %>% select(SamplingTimepoint, Facility, TREATMENT), 
                              col = list(SamplingTimepoint = col_timepoint_pup,
                                         TREATMENT = col_treatment, 
                                         Facility = col_facility),
                              simple_anno_size = unit(3, "mm"), 
                              annotation_label = c("Time point", "Facility", "Treatment"),
                              annotation_name_gp = gpar(fontsize = 7,fontface = "bold"), 
                              annotation_name_side = "left")
wft2 = wft %>% column_to_rownames(var = "taxa_long")
df_row_name_label = structure(rownames(wft2), names = rownames(wft2))
row_dend = as.dendrogram(hclust(dist(wft2)))
#### the heatmap below don't cluster column(sample), so samples are in orders
p = Heatmap(as.matrix(wft2), 
            col = mat_col_fun, 
            name = "Relative Abundance",
            heatmap_legend_param = list(at = c(-4, -3.3, -2.6, -1.9, -1.2, -0.5), 
                                        labels = c("0.01%", "0.05%", "0.25%", "1.25%", "6.25%", "31.25%"), 
                                        labels_gp = gpar(fontsize = 7), 
                                        title_gp = gpar(fontsize = 8, fontface = "bold")),
            cluster_columns = F, show_column_names = F,
            column_title_gp = gpar(fontsize = 7, fontface = "bold"),
            column_split = df_col$SamplingTimepoint,
            cluster_rows = row_dend,
            row_names_gp = gpar(fontsize = 8),
            row_labels = df_row_name_label,
            row_dend_width = unit(15, "mm"),
            row_names_max_width = max_text_width(df_row_name_label, gp = gpar(fontsize = 8)),
            top_annotation = column_ha,
            height = unit(8, "mm")*dim(wft)[1],
            width = unit(0.5, "mm")*dim(wft)[2]
            )
p1 = draw(p, heatmap_legend_side = "left", annotation_legend_side = "left")
pdf(file = paste0("output/taxa/maaslin2/pup_facility_by_week_heatmap_g.pdf"), 
    width = ComplexHeatmap:::width(p1) %>% as.numeric()/25.4, 
    height = ComplexHeatmap:::height(p1) %>% as.numeric()/25.4, useDingbats = F)
draw(p1)
dev.off()

row_ord = row_order(p1)
taxa_ord = rownames(wft2)[row_ord]
## all genus coef data
a = lapply(c("Week3","Week4","Week5","Week7","Week9","Week12"),
           function(x){res = read.delim(paste0("output/taxa/maaslin2/pups_",x, "_Genus/all_results.tsv"))
                       res$Group = x
                       res
           })  
res_m_pup_g = do.call(rbind, a) %>% mutate(feature = str_remove(feature,"^X")) %>% 
  left_join(taxa_new %>% select(id, taxa_long),by = c("feature"="id"))

mat1 = res_m_pup_g %>% filter(taxa_long %in% taxa_ord, metadata == "Facility") %>% 
  select(taxa_long, Group, coef) %>% pivot_wider(names_from = "Group", values_from = "coef") %>% 
  column_to_rownames(var = "taxa_long")
mat1 = mat1[taxa_ord,]

mat2 = res_m_pup_g %>% filter(taxa_long %in% taxa_ord, metadata == "Facility") %>% 
  select(taxa_long, Group, qval) %>% 
  mutate(qval = ifelse(qval< 0.1, as.character(round(qval,4)),"")) %>% 
  pivot_wider(names_from = "Group", values_from = "qval") %>% 
  column_to_rownames(var = "taxa_long")
mat2 = mat2[taxa_ord,]

df_row_name_label = structure(rownames(mat1), names = rownames(mat1))
p = Heatmap(as.matrix(mat1), 
            col = col_fun, 
            name = "Log2 Fold Change",
            heatmap_legend_param = list(at = c(-2, -1, 0, 1, 2), 
                                        labels = c("-2", "-1", "0", "1", "2"), 
                                        labels_gp = gpar(fontsize = 7), 
                                        title_gp = gpar(fontsize = 8, fontface = "bold")),
            cluster_columns = F, show_column_names = T,
            column_title_gp = gpar(fontsize = 7, fontface = "bold"),
            cluster_rows = F,
            row_names_gp = gpar(fontsize = 8),
            row_labels = df_row_name_label,
            row_dend_width = unit(15, "mm"),
            row_names_max_width = max_text_width(df_row_name_label, gp = gpar(fontsize = 8)),
            cell_fun = function(j,i, x, y, width, height, fill){
              grid.text(sprintf("%s", mat2[i, j]), x, y, gp = gpar(fontsize = 7))
            },
            height = unit(5, "in"),
            width = unit(10, "in")
            )
p1 = draw(p, heatmap_legend_side = "left", annotation_legend_side = "left")
pdf(file = paste0("output/taxa/maaslin2/pup_facility_by_week_heatmap_g_qval_fc.pdf"), 
    width = ComplexHeatmap:::width(p1) %>% as.numeric()/25.4, 
    height = ComplexHeatmap:::height(p1) %>% as.numeric()/25.4,
    useDingbats = F)
draw(p1)
dev.off()

```

#### maaslin2 heatmap genus by sex
```{r include=FALSE}
taxa_new = taxa %>% mutate(taxa_long = str_c(Kingdom,Phylum,Class,Order,Family,Genus,sep = ";"))
meta_all = phylo_rf@sam_data@.Data %>% as.data.frame()
names(meta_all) = phylo_rf@sam_data@names
meta_all$Sample_name = phylo_rf@sam_data@row.names
phylo_g = tax_glom(phylo_rf, taxrank = "Genus", NArm = F)
ft = otu_table(phylo_g@otu_table) %>% as.matrix() %>% as.data.frame() 


a = lapply(paste(rep(c("M","F"),each = 6),rep(c("Week3","Week4","Week5","Week7","Week9","Week12"),2),  sep = "_"),
           function(x){read.csv(paste0("output/taxa/maaslin2/summary_pups_",x, ".csv"))})  
res_all_sig = do.call(rbind, a) 

res_TREATMENT_g = res_all_sig %>% filter(metadata == "TREATMENT",level == "Genus") %>% 
  mutate(Sex = str_split(Group, "_", simplify = T)[,1],
         Timepoint = str_split(Group, "_", simplify = T)[,2]) 

res_Facility_g = res_all_sig %>% filter(metadata == "Facility",level == "Genus") %>% 
  mutate(Sex = str_split(Group, "_", simplify = T)[,1],
         Timepoint = str_split(Group, "_", simplify = T)[,2]) 

a = lapply(paste(rep(c("M","F"),each = 6),rep(c("Week3","Week4","Week5","Week7","Week9","Week12"),2),  sep = "_"),
           function(x){res = read.delim(paste0("output/taxa/maaslin2/pups_",x, "_Genus/all_results.tsv"))
                       res$Group = x
                       res
           })  
res_all_g = do.call(rbind, a) %>% mutate(feature = str_remove(feature,"^X")) %>% 
  left_join(taxa_new %>% select(id, taxa_long),by = c("feature"="id")) %>% 
  mutate(Sex = str_split(Group, "_", simplify = T)[,1],
         Timepoint = str_split(Group, "_", simplify = T)[,2])

for(v in c("TREATMENT", "Facility")){
  for(s in c("M", "F")){
    res_sig = res_all_sig %>% filter(metadata == v,level == "Genus") %>% 
      mutate(Sex = str_split(Group, "_", simplify = T)[,1],
             Timepoint = str_split(Group, "_", simplify = T)[,2])
    if(nrow(res_sig) > 50){
      res_sig$abs_FC = abs(res_sig$coef)
      res_sig = res_sig %>% arrange(desc(abs_FC)) %>% top_n(50) 
      picked_taxa = res_sig %>% filter(Sex == s) %>% pull(feature)
    }else{
      picked_taxa = res_sig %>% filter(Sex == s) %>% pull(feature)
    } 
    wmeta = meta_all %>% filter(Generation == "F1", Sex == s) %>% 
      mutate(SamplingTimepoint = factor(SamplingTimepoint, levels = c("Week3","Week4","Week5","Week7","Week9","Week12"), ordered = T)) 
    if(v == "TREATMENT"){
      wmeta = wmeta %>% arrange(SamplingTimepoint,TREATMENT, Facility)
      df_col = wmeta %>% select(SamplingTimepoint, TREATMENT, Facility)
      column_ha = HeatmapAnnotation(df = df_col, 
                                    col = list(SamplingTimepoint = col_timepoint_pup,
                                                TREATMENT = col_treatment, 
                                                Facility = col_facility),
                                    simple_anno_size = unit(3, "mm"), 
                                    annotation_label = c("Time point", "Treatment", "Facility"),
                                    annotation_name_gp = gpar(fontsize = 7,fontface = "bold"), 
                                    annotation_name_side = "left")
    }else{
      wmeta = wmeta %>% arrange(SamplingTimepoint,Facility,TREATMENT)
      df_col = wmeta %>% select(SamplingTimepoint, Facility,TREATMENT)
      column_ha = HeatmapAnnotation(df = df_col, 
                                    col = list(SamplingTimepoint = col_timepoint_pup,
                                               TREATMENT = col_treatment, 
                                               Facility = col_facility),
                                    simple_anno_size = unit(3, "mm"), 
                                    annotation_label = c("Time point", "Facility","Treatment"),
                                    annotation_name_gp = gpar(fontsize = 7,fontface = "bold"), 
                                    annotation_name_side = "left")
    }
    wft = ft[picked_taxa, wmeta %>% pull(Sample_name)]
    wft = log10((wft + 1)/colSums(ft[,-1])[1])
    wft = wft %>% rownames_to_column(var="id") %>% merge(taxa_new %>% select(id, taxa_long)) %>% select(!id) %>% select(taxa_long, everything())
    wft2 = wft %>% column_to_rownames(var = "taxa_long")
    df_row_name_label = structure(rownames(wft2), names = rownames(wft2))
    row_dend = as.dendrogram(hclust(dist(wft2)))
    p = Heatmap(as.matrix(wft2), 
                col = mat_col_fun, 
                name = "Relative Abundance",
                heatmap_legend_param = list(at = c(-4, -3.3, -2.6, -1.9, -1.2, -0.5), 
                                        labels = c("0.01%", "0.05%", "0.25%", "1.25%", "6.25%", "31.25%"), 
                                        labels_gp = gpar(fontsize = 7), 
                                        title_gp = gpar(fontsize = 8, fontface = "bold")),
                cluster_columns = F, show_column_names = F,
                column_title_gp = gpar(fontsize = 7, fontface = "bold"),
                column_split = df_col$SamplingTimepoint,
                cluster_rows = row_dend,
                row_names_gp = gpar(fontsize = 8),
                row_labels = df_row_name_label,
                row_dend_width = unit(15, "mm"),
                row_names_max_width = max_text_width(df_row_name_label, gp = gpar(fontsize = 8)),
                top_annotation = column_ha,
                height = unit(8, "mm")*dim(wft)[1],
                width = unit(0.5, "mm")*dim(wft)[2]
                )
    p1 = draw(p, heatmap_legend_side = "left", annotation_legend_side = "left")
    pdf(file = paste0("output/taxa/maaslin2/pup_", v, "_by_week_Sex_",s ,"_heatmap_g.pdf"), 
        width = ComplexHeatmap:::width(p1) %>% as.numeric()/25.4, 
        height = ComplexHeatmap:::height(p1) %>% as.numeric()/25.4, useDingbats = F)
    draw(p1)
    dev.off()
    row_ord = row_order(p1)
    taxa_ord = rownames(wft2)[row_ord]
    mat1 = res_all_g %>% filter(taxa_long %in% taxa_ord, metadata == v, Sex == s) %>% 
      select(taxa_long, Timepoint, coef) %>% pivot_wider(names_from = "Timepoint", values_from = "coef") %>% 
      column_to_rownames(var = "taxa_long")
    mat1 = mat1[taxa_ord,]
    
    mat2 = res_all_g %>% filter(taxa_long %in% taxa_ord, metadata == v, Sex == s) %>% 
      select(taxa_long, Timepoint, qval) %>% 
      mutate(qval = ifelse(qval< 0.1, as.character(round(qval,4)),"")) %>% 
      pivot_wider(names_from = "Timepoint", values_from = "qval") %>% 
      column_to_rownames(var = "taxa_long")
    mat2 = mat2[taxa_ord,]
    df_row_name_label = structure(rownames(mat1), names = rownames(mat1))
    p = Heatmap(as.matrix(mat1), 
                col = col_fun, 
                name = "Log2 Fold Change",
                heatmap_legend_param = list(at = c(-2, -1, 0, 1, 2), 
                                            labels = c("-2", "-1", "0", "1", "2"), 
                                            labels_gp = gpar(fontsize = 7), 
                                            title_gp = gpar(fontsize = 8, fontface = "bold")),
                cluster_columns = F, show_column_names = T,
                column_title_gp = gpar(fontsize = 7, fontface = "bold"),
                cluster_rows = F,
                row_names_gp = gpar(fontsize = 8),
                row_labels = df_row_name_label,
                row_dend_width = unit(15, "mm"),
                row_names_max_width = max_text_width(df_row_name_label, gp = gpar(fontsize = 8)),
                cell_fun = function(j,i, x, y, width, height, fill){
                  grid.text(sprintf("%s", mat2[i, j]), x, y, gp = gpar(fontsize = 7))
                },
                height = unit(5, "in"),
                width = unit(10, "in")
                )
    p1 = draw(p, heatmap_legend_side = "left", annotation_legend_side = "left")
    pdf(file = paste0("output/taxa/maaslin2/pup_", v, "_by_week_Sex_",s ,"_heatmap_g_qval_fc.pdf"), 
        width = ComplexHeatmap:::width(p1) %>% as.numeric()/25.4, 
        height = ComplexHeatmap:::height(p1) %>% as.numeric()/25.4,
        useDingbats = F)
    draw(p1)
    dev.off()
  }
} 

```






















